name: gliders_test
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alabaster=1.0.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - babel=2.17.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310hd8f1fbe_7
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - geographiclib=2.0=py310h06a4308_0
  - geopy=2.4.1=py310h06a4308_0
  - gsw=3.6.19=py310hf462985_1
  - idna=3.10=pyhd8ed1ab_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.34.0=pyh907856f_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openssl=3.5.2=h26f9b46_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py310h06a4308_0
  - platformdirs=4.3.7=pyh29332c3_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=5.9.0=py310h5eee18b_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=2_cp310
  - pytz=2025.1=pyhd8ed1ab_0
  - pyzmq=26.2.0=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=pyhd8ed1ab_1
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.2=py310h23a989f_1
  - setuptools=75.8.0=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sphinx=8.1.3=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - asciitree==0.3.3
      - astroid==3.3.9
      - cftime==1.6.4.post1
      - contourpy==1.3.1
      - cycler==0.12.1
      - fasteners==0.19
      - fonttools==4.56.0
      - h5netcdf==1.6.1
      - h5py==3.13.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - netcdf4==1.7.2
      - numcodecs==0.13.1
      - pandas==2.2.3
      - pillow==11.1.0
      - polars==1.30.0
      - pyparsing==3.2.3
      - pyyaml==6.0.2
      - seaborn==0.13.2
      - sphinx-autoapi==3.6.0
      - sphinxcontrib-serializinghtml==2.0.0
      - tzdata==2025.2
      - urllib3==2.3.0
      - xarray==2025.3.0
      - zarr==2.18.3
