name: mau_noc_fork
channels:
  - conda-forge
dependencies:
  # Core environment
  - python=3.10
  - pip
  - numpy=1.26
  - pandas=2.2
  - scipy=1.15
  - xarray=2025.3
  - netcdf4=1.7
  - h5py=3.13
  - h5netcdf=1.6
  - zarr=2.18
  - numcodecs=0.13
  - gsw=3.6
  - geopy=2.4
  - scikit-learn=1.7
  - matplotlib=3.10
  - seaborn=0.13
  - requests=2.32

  # Documentation and development tools
  - ipykernel
  - jupyterlab
  - sphinx=8.1
  - sphinx-autoapi=3.6
  - sphinx-rtd-theme
  - sphinxcontrib-napoleon
  - sphinxcontrib-serializinghtml
  - myst-parser
  - pytest
  - black
  - pre-commit

  # mau_noc_toolbox specific additions
  - bokeh

